/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminExamExamIdRouteImport } from './routes/admin.exam.$examId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamExamIdRoute = AdminExamExamIdRouteImport.update({
  id: '/admin/exam/$examId',
  path: '/admin/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/users': typeof AdminUsersRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/exam/$examId': typeof AdminExamExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/users': typeof AdminUsersRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/exam/$examId': typeof AdminExamExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/users': typeof AdminUsersRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/exam/$examId': typeof AdminExamExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/users'
    | '/exam/$examId'
    | '/admin/'
    | '/admin/exam/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/users'
    | '/exam/$examId'
    | '/admin'
    | '/admin/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/users'
    | '/exam/$examId'
    | '/admin/'
    | '/admin/exam/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExamExamIdRoute: typeof AdminExamExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exam/$examId': {
      id: '/admin/exam/$examId'
      path: '/admin/exam/$examId'
      fullPath: '/admin/exam/$examId'
      preLoaderRoute: typeof AdminExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminUsersRoute: AdminUsersRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminExamExamIdRoute: AdminExamExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
